export const contentModules = {
  projects: {
    title: "Projects",
    description: "Manage case studies shown in the public projects section.",
    api: "projects",
    columns: [["title", "Project"], ["category", "Category"], ["status", "Status"], ["displayOrder", "Order"]],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "slug", label: "Slug", hint: "Leave blank to generate from the title." },
      { name: "shortDescription", label: "Short description", type: "textarea" },
      { name: "description", label: "Detailed description", type: "textarea", rows: 5 },
      { name: "image", label: "Project thumbnail", type: "image", hint: "JPEG, PNG, WebP, or GIF, up to 5 MB." },
      { name: "technologies", label: "Technologies", type: "list", hint: "Separate values with commas." },
      { name: "category", label: "Category" },
      { name: "projectUrl", label: "Project URL", type: "url" },
      { name: "githubUrl", label: "GitHub URL", type: "url" },
      { name: "displayOrder", label: "Display order", type: "number" },
      { name: "isPublished", label: "Published on public site", type: "checkbox" },
    ],
    defaults: { technologies: [], displayOrder: 0, isPublished: false, status: "draft" },
    searchable: ["title", "category", "shortDescription"],
  },
  team: {
    title: "Our team",
    description: "Manage active team members and their public profiles.",
    api: "team",
    columns: [["name", "Name"], ["designation", "Designation"], ["isActive", "Visible"], ["displayOrder", "Order"]],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "designation", label: "Designation", required: true },
      { name: "image", label: "Profile image", type: "image", hint: "JPEG, PNG, WebP, or GIF, up to 5 MB." },
      { name: "bio", label: "Bio", type: "textarea" },
      { name: "linkedin", label: "LinkedIn URL", type: "url" },
      { name: "github", label: "GitHub URL", type: "url" },
      { name: "displayOrder", label: "Display order", type: "number" },
      { name: "isActive", label: "Visible on public site", type: "checkbox" },
    ],
    defaults: { displayOrder: 0, isActive: true },
    searchable: ["name", "designation", "bio"],
  },
  services: {
    title: "Services",
    description: "Manage the services displayed on the public website.",
    api: "services",
    columns: [["title", "Service"], ["isActive", "Active"], ["displayOrder", "Order"]],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "slug", label: "Slug", hint: "Leave blank to generate from the title." },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "icon", label: "Icon key", hint: "Examples: code, business, globe, marketing, mobile, analytics." },
      { name: "color", label: "Accent color", type: "color" },
      { name: "features", label: "Features", type: "list", hint: "Separate values with commas." },
      { name: "displayOrder", label: "Display order", type: "number" },
      { name: "isActive", label: "Active on public site", type: "checkbox" },
    ],
    defaults: { features: [], icon: "business", color: "#16806c", displayOrder: 0, isActive: true },
    searchable: ["title", "description"],
  },
  faqs: {
    title: "FAQ",
    description: "Keep common client questions accurate and useful.",
    api: "faqs",
    columns: [["question", "Question"], ["isActive", "Active"], ["displayOrder", "Order"]],
    fields: [
      { name: "question", label: "Question", required: true },
      { name: "answer", label: "Answer", type: "textarea", rows: 5, required: true },
      { name: "displayOrder", label: "Display order", type: "number" },
      { name: "isActive", label: "Active on public site", type: "checkbox" },
    ],
    defaults: { displayOrder: 0, isActive: true },
    searchable: ["question", "answer"],
  },
};